namespace: default

resources:
- manifest.yaml


configMapGenerator:
  - name: oneshot-cm
    literals:
      - ONESHOT_YAML=/tmp/oneshot/oneshot.yaml

secretGenerator:
- name: oneshot-secret
  files:
  - oneshot.yaml=oneshot.yaml
