resources:
- manifest.yaml


configMapGenerator:
  - name: oneshot-cm
    literals:
      - MASTER_DB_URL=postgres://postgres:postgres@192.168.0.24:5432/postgres
      - MAKER_YAML=/tmp/oneshot/oneshot.yaml

secretGenerator:
- name: oneshot-secret
  files:
  - oneshot.yaml=../oneshot.yaml