apiVersion: batch/v1
kind: Job
metadata:
  name: oneshot
spec:
  backoffLimit: 50
  activeDeadlineSeconds: 120
  template:
    spec:
      containers:
      - name: oneshot
        image: rosscdh/kubernetes-db-oneshot
        # lifecycle:
        #     postStart:
        #       exec:
        #         command: ["/bin/sh", "-c", "cp /tmp/oneshot/oneshot.yaml /oneshot/oneshot.yaml"]
        envFrom:
          - configMapRef:
              name: oneshot-cm
        volumeMounts:
        - name: oneshot-yaml
          mountPath: "/tmp/oneshot"
          readOnly: true
      restartPolicy: Never
      volumes:
      - name: oneshot-yaml
        secret:
          secretName: oneshot-secret
          items:
            - key: oneshot.yaml
              path: oneshot.yaml