apiVersion: batch/v1
kind: Job
metadata:
  name: oneshot
#  generatedName: oneshot-
spec:
  backoffLimit: 50
  activeDeadlineSeconds: 120
  ttlSecondsAfterFinished: 300
  template:
    spec:
      containers:
      - name: oneshot
        image: rosscdh/kubernetes-db-oneshot
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: oneshot-cm
        volumeMounts:
        - name: oneshot-yaml
          mountPath: "/tmp/oneshot"
          readOnly: true
      restartPolicy: Never
      volumes:
      - name: oneshot-yaml
        secret:
          secretName: oneshot-secret
          items:
            - key: oneshot.yaml
              path: oneshot.yaml
