apiVersion: batch/v1
kind: Job
metadata:
  name: oneshot
spec:
  backoffLimit: 15
  activeDeadlineSeconds: 100
  template:
    spec:
      containers:
      - name: oneshot
        image: rosscdh/kubernetes-db-oneshot
        envFrom:
          - secretRef:
              name: oneshot-cm
        volumeMounts:
        - name: oneshot-yaml
          mountPath: "/oneshot/oneshot.yaml"
          readOnly: true
      restartPolicy: Never
      volumes:
      - name: oneshot-yaml
        secret:
          secretName: oneshot-secret
          items:
            - key: oneshot.yaml
              # path: my-group/my-username