MASTER_DB_URL: postgresql://postgres:postgres@192.168.0.24:5432/postgres

create_dbs:
- url: postgresql://dbuserA:passwordA@192.168.0.24:5432/dba
- url: postgresql://dbuserB:passwordB@192.168.0.24:5432/dbb

statements:
  - GRANT SELECT ON ALL TABLES IN SCHEMA public TO dbuserBReader;
  - ALTER DEFAULT PRIVILEGES IN SCHEMA public
      GRANT SELECT ON TABLES TO dbuserBReader;

# MASTER_DB_URL: mysql://user:password@localhost:3306/mysql

# pre_statements: []

# create_dbs:
# - url: mysql://userA:passwordA@localhost:3306/dbA
# - url: mysql://userB:passwordB@localhost:3306/DbB

# statements: []
